### ISSUE TITLE
Solveurs linéaire : HSL vs MUMPS

### ISSUE THREAD

**Issue by 0Yassine0** [control-toolbox/CTBenchmarks.jl#3]

**Comment by frapac** [comment]
Les instructions pour utiliser HSL avec Ipopt peuvent se trouver ici : 
https://github.com/jump-dev/Ipopt.jl?tab=readme-ov-file#hsl

Il faut une adresse académique pour avoir une license HSL.

**Comment by ocots** [comment]
Avec l'aide de @amontoison, nous sommes en train d'intégrer la possibilité de choisir le solveur linéaire dans `OptimalControl`. Vois la discussion suivante : https://github.com/control-toolbox/CTDirect.jl/issues/69#issuecomment-2175008838. Je ne sais pas vraiment ce que cela implique comme changement au niveau de notre code.

**Comment by amontoison** [comment]
J'ai ouvert une PR: https://github.com/control-toolbox/CTDirect.jl/pull/113
